export const MOBILE_BREAKPOINT = 560;
export const REVIEW_TOOLTIP_MAX_WIDTH = 18 * 16;
export const REVIEW_TOOLTIP_VIEWPORT_INSET = 18;
export const REVIEW_TOOLTIP_VERTICAL_GAP = 10;
export const TOOLTIP_WIDTH = 320;
export const TOOLTIP_HEIGHT = 260;

export const GROUP_OPTION_KEYS = ['region', 'sector', 'style', 'risk'];
export const SCORE_AXIS_KEYS = [
  'profitability',
  'diversification',
  'riskManagement',
  'composition',
  'timing',
  'stability',
];

export const LANGUAGE_OPTIONS = ['ko', 'en'];
export const ASSET_CLASS_MODE_OPTIONS = ['auto', 'preferOriginal'];
export const ALLOCATION_WEIGHT_MODE_OPTIONS = ['auto', 'stock', 'assetClass', 'account'];
export const SCORE_WEIGHT_PRESET_OPTIONS = ['balanced', 'returnFocus', 'longTermReturnFocus', 'stabilityFocus'];

export const STORAGE_KEYS = {
  language: 'atom-sketch-language',
  assetClassMode: 'atom-sketch-asset-class-mode',
  allocationWeightMode: 'atom-sketch-allocation-weight-mode',
  scoreWeightPreset: 'atom-sketch-score-weight-preset',
  settingsDockPosition: 'atom-sketch-settings-dock-position',
  toolTriggerPosition: 'atom-sketch-tool-trigger-position',
  groupDockPosition: 'atom-sketch-group-dock-position',
  heatmapDockPosition: 'atom-sketch-heatmap-dock-position',
  scoreDockPosition: 'atom-sketch-score-dock-position-v2',
  allocationDockPosition: 'atom-sketch-allocation-dock-position',
};

export const ALLOCATION_SEGMENT_PALETTE = [
  {
    main: '#f2f2f2',
    soft: 'rgba(242, 242, 242, 0.34)',
    glow: 'rgba(242, 242, 242, 0.18)',
    highlight: 'rgba(255, 255, 255, 0.78)',
  },
  {
    main: '#d6d6d6',
    soft: 'rgba(214, 214, 214, 0.34)',
    glow: 'rgba(214, 214, 214, 0.18)',
    highlight: 'rgba(247, 247, 247, 0.66)',
  },
  {
    main: '#bdbdbd',
    soft: 'rgba(189, 189, 189, 0.34)',
    glow: 'rgba(189, 189, 189, 0.18)',
    highlight: 'rgba(234, 234, 234, 0.6)',
  },
  {
    main: '#a4a4a4',
    soft: 'rgba(164, 164, 164, 0.34)',
    glow: 'rgba(164, 164, 164, 0.18)',
    highlight: 'rgba(223, 223, 223, 0.58)',
  },
  {
    main: '#8a8a8a',
    soft: 'rgba(138, 138, 138, 0.34)',
    glow: 'rgba(138, 138, 138, 0.18)',
    highlight: 'rgba(212, 212, 212, 0.56)',
  },
  {
    main: '#727272',
    soft: 'rgba(114, 114, 114, 0.34)',
    glow: 'rgba(114, 114, 114, 0.18)',
    highlight: 'rgba(198, 198, 198, 0.54)',
  },
];

export const UI_TEXT = {
  ko: {
    groupLabels: {
      region: '투자 지역',
      sector: '분야',
      style: '투자 스타일',
      risk: '위험 등급',
    },
    scoreAxisLabels: {
      profitability: '수익성',
      diversification: '분산투자',
      riskManagement: '위험관리',
      composition: '포트폴리오 구성',
      timing: '투자 타이밍',
      stability: '수익 안정성',
    },
    fieldLabels: {
      stockCode: '종목코드',
      stockName: '종목명',
      accountId: '계좌 ID',
      accountType: '계좌유형',
      buyDate: '매수일',
      buyPrice: '매수가',
      shares: '보유수량',
      return: '수익률',
      region: '투자 지역',
      sector: '분야',
      style: '투자 스타일',
      risk: '위험 등급',
      assetClass: '자산 구분',
      currency: '통화',
      marketCapClass: '규모 분류',
      volatility: '변동성',
      taxStatus: '과세 구분',
      benchmark: '비교 지수',
    },
    settings: '설정',
    language: '언어',
    korean: '한국어',
    english: '영어',
    settingsAria: '설정 열기',
    settingsSectionLanguage: '언어',
    settingsSectionAssetClassMode: '자산군 분류 방식',
    settingsSectionAllocationWeightMode: '도넛 차트 표시 기준',
    settingsSectionScoreWeightPreset: '스파이더 차트 축 가중치',
    settingsSectionLayoutReset: '배치 초기화',
    settingsAssetClassAuto: '자동 분류',
    settingsAssetClassPreferOriginal: '원본 자산군 우선',
    settingsAllocationWeightAuto: '자동',
    settingsAllocationWeightStock: '종목별 비중',
    settingsAllocationWeightAssetClass: '자산군 기준',
    settingsAllocationWeightAccount: '계좌 기준',
    settingsScoreWeightBalanced: '균형 중심',
    settingsScoreWeightReturnFocus: '수익 중심',
    settingsScoreWeightLongTermReturnFocus: '장기수익 중심',
    settingsScoreWeightStabilityFocus: '안정 중심',
    settingsResetLayoutAction: '현재 배치 다시 맞추기',
    uploadAria: '투자 데이터 업로드',
    uploadHint: '투자 데이터를 업로드 해주세요',
    uploadDragHint: '파일을 여기에 끌어다 놓거나 클릭해서 업로드',
    reviewTitle: '업로드 진단',
    reviewStatusOk: '정상',
    reviewStatusNeedsReview: '검토 필요',
    reviewStatusBlocked: '차단',
    toolMenuAria: '도구 선택 열기',
    groupToolAria: '하이라이트 도구 열기',
    scoreToolAria: '스파이더 차트 열기',
    clearUploadAria: '업로드 파일 지우기',
    clearCenterAria: '선택 강조 해제',
    heatmapAria: '수익 캘린더 히트맵 열기',
    contributionAria: '깃허브 잔디밭 아이콘',
    heatmapChartAria: '포트폴리오 수익 캘린더 히트맵',
    heatmapHint: '날짜 위에 커서를 올려 손익 확인',
    heatmapEmpty: '날짜와 손익 데이터가 없어 히트맵을 표시할 수 없습니다.',
    heatmapLess: '적음',
    heatmapMore: '많음',
    scoreChartAria: '포트폴리오 레이더 점수 차트',
    allocationTitle: '자산 비중',
    allocationChartAria: '포트폴리오 자산 비중 도넛 차트',
    allocationTotalReturn: '총 수익률',
    allocationUnknown: '미분류',
    allocationShareLabel: '전체 비중',
    allocationSourceExplicit: '비중 컬럼 기준',
    allocationSourcePosition: '매수가 × 수량 기준',
    allocationSourceEqual: '균등 비중 기준',
    atomAria: '검은 배경 위 손으로 그린 인터랙티브 원자 스케치',
    scorePointUnit: '점',
    parseError: '종목 행을 찾지 못했습니다. ticker/name 컬럼이 있는 CSV를 올려주세요.',
    readError: '파일을 읽지 못했습니다.',
    maxFilesError: '포트폴리오는 최대 12개까지 업로드할 수 있습니다.',
    processingFile: '파일 처리 중...',
    dropToUpload: '놓아서 업로드',
  },
  en: {
    groupLabels: {
      region: 'Region',
      sector: 'Field',
      style: 'Style',
      risk: 'Risk Level',
    },
    scoreAxisLabels: {
      profitability: 'Profitability',
      diversification: 'Diversification',
      riskManagement: 'Risk Control',
      composition: 'Composition',
      timing: 'Timing',
      stability: 'Stability',
    },
    fieldLabels: {
      stockCode: 'Ticker',
      stockName: 'Name',
      accountId: 'Account ID',
      accountType: 'Account Type',
      buyDate: 'Buy Date',
      buyPrice: 'Buy Price',
      shares: 'Shares',
      return: 'Return',
      region: 'Region',
      sector: 'Field',
      style: 'Style',
      risk: 'Risk Level',
      assetClass: 'Asset Class',
      currency: 'Currency',
      marketCapClass: 'Market Cap',
      volatility: 'Volatility',
      taxStatus: 'Tax Status',
      benchmark: 'Benchmark',
    },
    settings: 'Settings',
    language: 'Language',
    korean: 'Korean',
    english: 'English',
    settingsAria: 'Open settings',
    settingsSectionLanguage: 'Language',
    settingsSectionAssetClassMode: 'Asset Class Mode',
    settingsSectionAllocationWeightMode: 'Donut Weight Basis',
    settingsSectionScoreWeightPreset: 'Spider Axis Weights',
    settingsSectionLayoutReset: 'Dock Layout Reset',
    settingsAssetClassAuto: 'Auto classify',
    settingsAssetClassPreferOriginal: 'Prefer original class',
    settingsAllocationWeightAuto: 'Auto',
    settingsAllocationWeightStock: 'By security weight',
    settingsAllocationWeightAssetClass: 'By asset class',
    settingsAllocationWeightAccount: 'By account',
    settingsScoreWeightBalanced: 'Balanced',
    settingsScoreWeightReturnFocus: 'Return focus',
    settingsScoreWeightLongTermReturnFocus: 'Long-term return',
    settingsScoreWeightStabilityFocus: 'Stability focus',
    settingsResetLayoutAction: 'Realign current docks',
    uploadAria: 'Upload investment data',
    uploadHint: 'Please upload your investment data',
    uploadDragHint: 'Drop files here or click to upload',
    reviewTitle: 'Upload Review',
    reviewStatusOk: 'OK',
    reviewStatusNeedsReview: 'Needs Review',
    reviewStatusBlocked: 'Blocked',
    toolMenuAria: 'Open tool picker',
    groupToolAria: 'Open highlight tool',
    scoreToolAria: 'Open radar chart',
    clearUploadAria: 'Clear uploaded file',
    clearCenterAria: 'Clear highlighted atom selection',
    heatmapAria: 'Open profit calendar heatmap',
    contributionAria: 'GitHub contribution icon',
    heatmapChartAria: 'Portfolio profit calendar heatmap',
    heatmapHint: 'Hover a date to inspect the result',
    heatmapEmpty: 'No date and return data was found for the heatmap.',
    heatmapLess: 'Less',
    heatmapMore: 'More',
    scoreChartAria: 'Portfolio radar score chart',
    allocationTitle: 'Asset Mix',
    allocationChartAria: 'Portfolio asset allocation donut chart',
    allocationTotalReturn: 'Total Return',
    allocationUnknown: 'Unclassified',
    allocationShareLabel: 'Portfolio Share',
    allocationSourceExplicit: 'Weighted by allocation column',
    allocationSourcePosition: 'Weighted by buy price × shares',
    allocationSourceEqual: 'Weighted equally',
    atomAria: 'Interactive hand-drawn atom sketch on a black background',
    scorePointUnit: 'pts',
    parseError: 'Could not find portfolio rows. Upload a CSV with ticker or name columns.',
    readError: 'Could not read the file.',
    maxFilesError: 'You can upload up to 12 portfolios.',
    processingFile: 'Processing file...',
    dropToUpload: 'Drop to upload',
  },
};
